/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Pedro
 */
public class Central extends javax.swing.JFrame {

    /**
     * Creates new form Central
     */
    public Central() {}
    public Central(String userRole, String userId) {
        initComponents();

        if (!userRole.equals("") || userRole != null) {
            if (userRole.toLowerCase().equals("admin")) {
                User manageUsersScreen = new User();
                this.jTabbedPane.addTab("Users", manageUsersScreen.getContentPane());
            } else if (userRole.toLowerCase().equals("employee")) {
                Order newOrderScreen = new Order(userId);
                ListOrders listOrdersScreen = new ListOrders();

                newOrderScreen.setLayout(new BorderLayout());
                this.jTabbedPane.addTab("New Order", newOrderScreen.getContentPane());
                this.jTabbedPane.addTab("List Orders", listOrdersScreen.getContentPane());
                // this.jTabbedPane.getTabComponentAt(0).setSize(485, 388);
                // .setSize(485, 388)
                
                this.jTabbedPane.addChangeListener(new ChangeListener() {
                    @Override
                    public void stateChanged(ChangeEvent e) {
                        if (e.getSource() instanceof JTabbedPane) {
                            JTabbedPane pane = (JTabbedPane) e.getSource();

                            if (pane.getTitleAt(pane.getSelectedIndex()).equals("List Orders")) {
                                listOrdersScreen.refreshOrdersTable("refresh");
                            }
                            // System.out.println("Selected pane: " + pane.getTitleAt(pane.getSelectedIndex()));
                            // System.out.println("Selected paneNo : " + pane.getSelectedIndex());
                        }
                    }
                });
            } else if (userRole.toLowerCase().equals("manager")) {
                Product productsScreen = new Product();
                ListOrders listOrdersScreen = new ListOrders();

                this.jTabbedPane.addTab("Products", productsScreen.getContentPane());
                this.jTabbedPane.addTab("List Orders", listOrdersScreen.getContentPane());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new java.awt.GridLayout());

        jTabbedPane.setToolTipText("");
        getContentPane().add(jTabbedPane);
        jTabbedPane.getAccessibleContext().setAccessibleName("TabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Central().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
